music/urls.py
from django.urls import path
from django.conf.urls import url
from . import views


app_name = 'music'

urlpatterns = [

 # music/
    path('',views.IndexView.as_view(),name = 'index'),

    #music/songs/
    path('songs/',views.IndexView1.as_view(),name = 'index1'),

    #music/search/q?=
    path('search/',views.search,name = 'search'),

    #music/login/
    path('login/',views.loginuser ,name='login'),

    #music/id/favorite
    url(r'^(?P<song_id>[0-9]+)/favorite/$',views.favorite,name = 'favorite'),

    #music/register/
     path('register/',views.UserFormView.as_view(),name = 'register'),

    #music/logout/
    path('logout/',views.logoutuser,name = 'logout'),

     #music/id/
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name = 'detail'),

    #music/album/add/
    url(r'album/add/$',views.AlbumCreate.as_view(),name = 'album_add'),

    #music/song/add/
    url(r'song/add/$',views.SongCreate.as_view(),name = 'song_add'),

    #music/album/2/
    url(r'album/(?P<pk>[0-9]+)/$',views.AlbumUpdate.as_view(),name = 'album_update'),

    #music/album/2/delete
    url(r'album/(?P<pk>[0-9]+)/delete/$',views.AlbumDelete.as_view(),name = 'album_delete')
]

website01/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('music/',include('music.urls')),
    path('admin/', admin.site.urls),

]

if settings.DEBUG :
    urlpatterns  += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Album(models.Model):
      artist           = models.CharField(max_length=50)
      album_title      = models.CharField(max_length = 100)
      genre           = models.CharField(max_length=50)
      album_logo      = models.FileField()

      def __str__(self):
        return self.album_title + '- ' + self.artist

      # to add new albums and to get the primary key value into self
      def get_absolute_url(self):
            return reverse('music:detail', kwargs = {'pk': self.pk})

class Song(models.Model):
      album           = models.ForeignKey(Album,on_delete = models.CASCADE)
      file_type       = models.CharField(max_length=10)
      song_title      = models.CharField(max_length=200)
      song_length     = models.CharField(max_length=30)
      is_Favorite     = models.BooleanField(default = False)

      def __str__ (self):
            return self.song_title

      #while adding new songs to get primary key into self

      def get__absolute__url(self):
            return reverse ('music:index1' , kwargs = {'pk':self.pk})

music/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','email','password']

class LoginForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','password']

music/views.py
from django.contrib.auth.decorators import login_required
from django.views import generic
from .models import Album,Song
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from django.db.models import Q
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import authenticate,login
from django.contrib.auth import logout
from django.views.generic import View
from .forms import UserForm
from django.contrib.auth.mixins import LoginRequiredMixin

class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = "all_albums"

    def get_queryset(self):
        return Album.objects.all()

class IndexView1(generic.ListView):
    template_name = 'music/index1.html'
    context_object_name = "all_songs"

    def get_queryset(self):
        return Song.objects.all()

class DetailView(generic.DetailView):

    template_name = 'music/detail.html'
    model = Album



class AlbumCreate(CreateView):
    model = Album
    fields = ['artist','album_logo','genre','album_title']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist','album_logo','genre','album_title']

class AlbumDelete(DeleteView,LoginRequiredMixin):
     model = Album
     raise_exception = True
     success_url = reverse_lazy('music:index')
  #  raise_exception = True


class SongCreate(CreateView):
    model = Song
    fields = ['song_title','song_length','album','is_Favorite']



class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration.html'

    def get(self,request):
        form = self.form_class(None)
        return render(request,self.template_name,{'form':form })

    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit = False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()


            user = authenticate(username = username,password = password)
            if user is not None:
                if user.is_active:
                    login(request,user)
                    return redirect('music:login')
        return render(request,self.template_name,{'form':form})

def search(request):

     if request.user.is_authenticated:
        albums = Album.objects.all()
        songs = Song.objects.all()
        query = request.GET.get("q")

        if query:
            albums = albums.filter(
                Q(album_title__icontains = query)|
                Q(artist__icontains = query)
                ).distinct()

            songs = songs.filter(
            Q(song_title__icontains = query),
            ).distinct()

            return render(request,'music/search.html',{
            'albums':albums,
            'songs':songs,
            'query' : query,
            })
        else:
            return(request,'music/search.html' ,{
            'albums' : albums})



def logoutuser(request):
    logout(request)
    form  = UserForm(request.POST or None)
    return render(request,'music/logout.html',{'form':form})



def loginuser(request):

    if request.method == "GET":
        return render(request,'music/login.html',{} )

    if  request.method == "POST" :

        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username = username,password = password)

        if user is not None:
                return redirect('music:index')

        return render(request,'music/login.html',{ 'error' : 1 ,'username': "Username or Password is Incorrect" } )
    return render(request,'music/login.html',{'error': 1 })


def favorite(request, song_id):

    song = get_object_or_404(Song, pk = song_id)
    try:
        if song.is_Favorite  :
            song.is_Favorite = False
            song.save()
            return redirect("music:index1")
    except (KeyError, Song.DoesNotExist):
        return render(request, 'music/index1.html', {'song': song})

    else:
            song.is_Favorite = True
            song.save()
            return redirect("music:index1")

music/templates/music/album_form.html
{% extends 'music/base.html' %}

{% block title %} Add Albums {% endblock %}


{% block body %}
<div class = "container-fluid">
    <div class ="row">
        <div class = "col-sm-12 col-md-7">
        <div class = "panel panel-default">
            <div class = "panel-body">
                <form class = "form-horizontal" action = "" method = "post" enctype = "multipart/form-data">
                    {% csrf_token %}
                    {% include 'music/form-template.html' %}

                    <div class = "form-group">
                        <div class = "col-sm-offset-2 col-sm-10">
                            <button type = "submit" class = "btn btn-success"> Submit </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        </div>
    </div>
</div>


{% endblock %}

music/templates/music/base.html
<html>
<head>
<title>{% block title %} Viberr {% endblock %} </title>

    {% load staticfiles %}
    {% load staticfiles %}
<link rel = "stylesheet" type = "text/css" href = "{% static 'music/style.css' %}" />
<link rel = "stylesheet" href = "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
<script src = "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel = "stylesheet" type = "text/css" href = "{% static 'music/style.css' %}" />

</head>
<body>
    <nav class = "navbar navbar-inverse" >
    <div class = "container-fluid">


        <!--Header-->
        <div class = "navbar-header" >
            <button type = "button" class = "navbar-toggle" data-toggle = "collapse" data-target = "#topNavBar">
                <span class = "icon-bar"></span>
                <span class = "icon-bar"></span>
                <span class = "icon-bar"></span>
            </button>
            <a class = "navbar-brand" href = "{% url 'music:index' %}"> Viberr </a>
        </div>

        <!--Items-->
        <div class = "collapse navbar-collapse">
            <ul class = "nav navbar-nav">
                <li class = "active">
                    <a href = "{% url 'music:index' %}">
                        <span class = "glyphicon glyphicon-cd" aria-hidden = "true"></span>&nbsp;
                        Albums
                    </a>
                </li>
                 <li class = "active">
                    <a href = "{%url 'music:index1' %}">
                        <span class = "glyphicon glyphicon-music" aria-hidden = "true"></span>&nbsp;
                        Songs
                    </a>
                </li>

            </ul>

            <form class = "navbar-form navbar-left" role = "search" method = "get" action = "{% url 'music:search' %}">
                <div class = "form-group">
                    <input type="text" class="form-control" name = "q" value = "{{request.GET.q}}"/>
                </div>
                <button type = "submit" class = "btn btn-default">Search</button>
            </form>
            <ul class = "nav navbar-nav navbar-right">
                <li class = "active">
                    <a href = "{% url 'music:album_add' %}">
                        <span class = "glyphicon glyphicon-plus" aria-hidden = "true"></span> &nbsp;
                        Add Albums
                    </a>
                </li>
                <li class = "active">
                    <a href = "{% url 'music:logout' %}">
                        <span class = "glyphicon glyphicon-off" aria-hidden = "true"></span> &nbsp;
                        Log out
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
    {% block body %}
    {% endblock %}
<footer> Hosted by : T.V.Abhishek,CBIT,Hyderabad</footer>
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %} Album Details {% endblock %}


{% block body %}
<div class = "col-sm-3">
<div class = "panel panel-default">
            <div class = "panel-body">

                <img src = "{{album.album_logo.url}}" height = "220" width="220">

<h1> {{ album.album_title }}</h1>
<h3> {{ album.artist }} </h3>
            </div>
    </div>
</div>


            <div class = "col-sm-8">
                <div class = "panel panel-default">
                    <div class = "panel-body">
                <form action = "{% url 'music:detail' album.id %} " method = "get" style = "display:inline">
                    {% csrf_token %}
                    <button type = "submit" class = "btn btn-default btn-sm">
                        View All songs
                    </button>
                </form>

                 <form action = "{% url 'music:song_add' %}" method = "post" style = "display:inline " >
                     {% csrf_token %}
                     <button type = "submit" class = "btn btn-default btn-success">
                         Add Song
                     </button>



                 </form><br><br>
                        <table width = "80%" cellpadding="30px">
                            <thead>
                            <th> Song Title  </th>
                            <th> Artist      </th>
                            <th>Song Length      </th>
                            </th>
                            </thead>
                               {% for song in album.song_set.all %}
                                <tr>
                                <td>{{ song.song_title }}</td>
                                <td>{{ song.album.artist }}</td>
                                <td>{{ song.song_length }}</td>
                                <td>{% if song.is_Favorite %}
                                    <img src = "../../static/music/images/star.jpg" height = "15" widht = "25"/>
                                    {% else %}
                                      &nbsp; <img src="../../static/music/images/star1.jpg" height = "13" width = "12"/>
                                    {% endif %}
                                </td>
                                </tr>
                                {% endfor %}
                        </table>

 </div>
 </div>
</div>
{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
    <div class = "form-group">
        <div class = "col-sm-offset-2 col-sm-10">
            <span class = "text-danger small">{{ field.errors}}</span>
        </div>
        <label class = "control-label col-sm-2" > {{field.label_tag }}
        </label>
        <div class = "col-sm-10">{{ field }} </div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block title %} Viberr {% endblock %}

{% block body %}

{% if all_albums %}
    <h3> ALBUMS:</h3><br>
    {% for album in all_albums %}



            <div class = "col-sm-3">
                <div class = "col-xs-12">
         <div class = "panel panel-default">
            <div class = "panel-body">


                <img src = "{{album.album_logo.url}}" height = "220" width="220">
        <h4> {{ album.album_title }}</h4>


    <!--Details-->
     <form action = "{% url 'music:detail' album.id %}" method = "get">
         {% csrf_token %}
         <button type = "submit" class = "btn btn-default btn-success">
            Details
         </button>
     </form>
    <!--Delete-->
       <form action = "{% url 'music:album_delete' album.id %}" method = "post" >
        {% csrf_token %}
        <input type = "hidden" name = "album_id" value = "{{album_id}}"/>
        <button type = "submit" class = "btn btn-default btn-sm" style = "display:inline" >
        <span class = "glyphicon glyphicon-trash" ></span>
        </button>
       </form>

            </div>

                     </div>
                </div>
            </div>

    {% endfor %}
{% else %}
    <h3> You don't have any Albums</h3>
    {% endif %}
{% endblock %}

music/templates/music/index1.html
{% extends 'music/base.html' %}
{% block title %} Songs List {% endblock %}

{% block body %}
{% if all_songs %}
    <h3> SONGS: </h3>
            <div class = "col-sm-2"></div>
                <div class = "col-sm-8">
         <div class = "panel panel-default">
            <div class = "panel-body ">

                <table width = "60%">
                    <thead>
                    <th> Song Title</th>
                    <th> Song Length </th>
                    <th> Artist </th>
                    <th> Liked </th>
                    </thead>

                        {% for song in all_songs %}
                            <tr>
                            <td>{{ song.song_title }}</td>
                            <td>{{ song.song_length }}</td>
                            <td>{{ song.album.artist }}</td>
                            <td>
                                 <form action = "{% url 'music:favorite' song.id %}" method = "post" name = "Song">
                                {% csrf_token %}

                                     {% if song.is_Favorite %}
                                    <img src = "../../static/music/images/star.jpg"  height = "15"  width = "25" />

                                 {% else %}
                                      &nbsp;&nbsp;<img src = "../../static/music/images/star1.jpg"  height = "13"  width = "13" />
                                 {% endif %}
                            <input type  = "submit" class = "btn btn-success" value = "Fav" />

                                </form>
                            </td>
                            </tr>
                        {% endfor %}

                </table>


      </div> </div></div>
{% endif %}
{% endblock %}

music/templates/music/login.html
{% extends 'music/base.html' %}
{% block title %}User Login {% endblock %}


{% block body %}

<h2 align = "left" > Welcome</h2>

{% if error %}
    <h2> {{ username }}</h2>
{% endif %}
<nav class = "navbar navbar-inverse">
    <div class = "col-sm-4"></div>
        <div class ="col-sm-4">
            <div class = "panel panel-default">
                <div class = "panel-body">
                    <
                    <ul class = "nav navbar-nav" >
                        <li class = "active">
                            <a href = "{% url 'music:login' %}">
                                <span class = "glyphicon glyphicon-user" aria-hidden = "true">&nbsp;
                                    Login
                                </span>
                        </a>
                        </li>
                        <li class = "active">
                            <a href = "{% url 'music:register' %}">
                                <span class = "glyphicon glyphicon-notes" aria-hidden = "true">&nbsp;
                                    Register
                                </span>
                            </a>
                        </li>
                    </ul>
                    </div>
            </div>


            <div class = "panel panel-default">


                <form class = "form-horizontal" action = "" method = "post" enctype = "multipart/form-data">
                    {% csrf_token %}
                         <div class = " panel-body"><br>
                             <div style = "text-align :center">
                            Username <input type = "text" name = "username"/><br><br>
                            Password <input type = "text"  name = "password"/><br><br>


                                 <button type = "submit"  class = "btn btn-success"> Submit </button>
                             </div>
                        </div>
                </form>

            </div>
        </div>
</nav>

{% endblock %}

music/templates/music/logout.html
<html>
<title>Logged Out</title>

<body>

<h2>YOU HAVE BEEN LOGGED OUT</h2>

</body>
</html>

music/templates/music/registration.html
{% extends 'music/base.html' %}
{% block title %}Register for The Site {% endblock %}

{% block body %}
<body background="../../static/music/images/bgimages.jpg">
<div class = "container-fluid">
    <div class ="row">
        <div class = "col-sm-12 col-md-7">
        <div class = "panel panel-default">
            <div class = "panel-body">
                <form class = "form-horizontal" action = "" method = "post" enctype = "multipart/form-data">
                    {% csrf_token %}
                    {% include 'music/form-template.html' %}

                    <div class = "form-group">
                        <div class = "col-sm-offset-2 col-sm-10">
                            <button type = "submit" class = "btn btn-success"> Submit </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/search.html
{% extends 'music/base.html' %}
{% block title %} Search: Song {% endblock %}



{% block body %}


            <h3> Showing results for : {{ query }}  </h3>

        {% if songs %}
        <div class = "row">
            <div class = "col-sm-2"></div>
            <div class = "col-sm-7">
                <strong>SONGS</strong>
                <div class = "panel panel-default">
                    <div class = "panel-body">

        <table width = "70%">
            <thead>
            <th> Song Title </th>
            <th>  From Album</th>
            <th> Song Length </th>
            </thead>



    {% for song in songs %}
        <tr>
            <td><a href = "#" >{{ song.song_title }}</a> </td>
            <td> {{ song.album.album_title }}</td>
            <td> {{ song.song_length }}</td>
        </tr>
    {% endfor %}
        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

    {% if albums %}
    <div class = "row">
            <div class = "col-sm-2"></div>
            <div class = "col-sm-7">
                <strong>ALBUMS</strong>
                <div class = "panel panel-default">
                    <div class = "panel-body">



    {% for album in albums %}
                        <h3>{{ album.album_title }} </h3><br>
                        <h4>{{album.album_artist }}</h4>
             <img src = "{{ album.album_logo.url }}" height = "220" width = "220">


    {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    {% endif %}



{% endblock %}

music/templates/music/song_form.html
{% extends 'music/base.html' %}

{% block title %} Add Songs {% endblock %}


{% block body %}
<div class = "container-fluid">
    <div class ="row">
        <div class = "col-sm-12 col-md-7">
        <div class = "panel panel-default">
            <div class = "panel-body">
                <form class = "form-horizontal" action = "{% url 'music:index1'%}" method = "get" enctype = "multipart/form-data">
                    {% csrf_token %}
                    {% include 'music/form-template.html' %}

                    <div class = "form-group">
                        <div class = "col-sm-offset-2 col-sm-10">
                            <button type = "submit" class = "btn btn-success"> Submit </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        </div>
    </div>
</div>
{% endblock %}